[build]
builder = "NIXPACKS"
buildCommand = "prisma generate --schema=backend/prisma/schema.prisma"

[deploy]
startCommand = "python -m backend.main"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
